spring:
  application:
    name: eureka-registry-producer

server:
  port: 2001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/