spring:
  application:
    name: eureka-registry-consumer-ribbon

server:
  port: 3002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/